title: Mercy hub
description: A compiled list of useful developer tools
theme: jekyll-theme-midnight 
owner_name: Mercy
github_username: omerciless
email: ohmerciless@gmail.com
author: oMerciless
  name: Mercy
show_downloads: true
